#!/bin/bash

# Wersja RPi dla generowanego obrazu.
#
rpi="bcm2710"
wersja="21.02.1"
link="https://downloads.openwrt.org/releases"

usage()
{
    echo "
Jak używać: wrt-rpi+ [ -w wersja ] [ -c ] | [ -h ]
 -w wersja OpenWRT do budowy (domyślne: $wersja)
 -c czyści swoje pliki z systemu
 -h wyświetlenie tej instrukcji
"
}

if [ "$#" = 0 ]; then
    usage
    echo
fi

while [ "$1" != "" ]; do
    case $1 in
        -w | --wersja )         shift
                                wersja=$1
                                ;;
        -c | --clean )          clean="yes"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

cd
if [ "$clean" = "yes" ]; then
    echo "Czyszczę ..."
    rm -rf $HOME/wrt-config
    rm -rf $HOME/wrt-$wersja
    rm -rf $HOME/openwrt-$wersja-images
    exit 0
fi

#if [ ! -d wrt-config ]; then
#    echo
#    echo "Nie ma na dysku konfiguracji dla OpenWRT ( katalog wrt-config )."
#    echo
#    git clone https://github.com/zbychuk79/wrt-config.git
#fi

if [ ! -d $HOME/wrt-$wersja/openwrt-imagebuilder-$wersja-bcm27xx-$rpi.Linux-x86_64 ]; then
    echo "Pobieram ..."
    mkdir -p $HOME/wrt-$wersja
    cd $HOME/wrt-$wersja
    echo "$link/$wersja/targets/bcm27xx/$rpi/openwrt-imagebuilder-$wersja-bcm27xx-$rpi.Linux-x86_64.tar.xz"
    wget -c $link/$wersja/targets/bcm27xx/$rpi/openwrt-imagebuilder-$wersja-bcm27xx-$rpi.Linux-x86_64.tar.xz
    tar xvfJ openwrt-imagebuilder-$wersja-bcm27xx-$rpi.Linux-x86_64.tar.xz
fi

echo "Generuję obrazy ..."
for ap in router_rpi3plus; do
    # RPi 3B+ i rtl8152 USB Ethernet jako WAN
    cd $HOME/wrt-$wersja/openwrt-imagebuilder-$wersja-bcm27xx-$rpi.Linux-x86_64
    make image PACKAGES="luci luci-app-firewall luci-base luci-lib-ip luci-lib-jsonc \
    luci-lib-nixio luci-mod-admin-full luci-proto-ipv6 luci-proto-ppp luci-theme-bootstrap \
    mc curl nano kmod-usb-net-rtl8152" #FILES=../../wrt-config/$ap/
    mkdir -p $HOME/openwrt-$wersja-images/$ap
    mv bin/targets/bcm27xx/$rpi/* $HOME/openwrt-$wersja-images/$ap
    cd
    #tar cvfJ $HOME/openwrt-$wersja-images/$ap/$ap-config.tar.xz wrt-config/$ap
done
cp $0 $HOME/openwrt-$wersja-images/
